--- #YAML:1.0
name:               Parse-Syslog-Line
version:            0.7
abstract:           Parses Syslog Lines into Hashes
author:
    - Brad Lhotsky <brad@divisionbyzero.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    DateTime::Format::HTTP:  0
    Readonly:             0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
