---
abstract: 'Simple syslog line parser'
author:
  - 'Brad Lhotsky <brad@divisionbyzero.net>'
build_requires:
  Data::Dumper: '0'
  DateTime: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Parse-Syslog-Line
requires:
  Const::Fast: '0'
  DateTime::Format::HTTP: '0'
  Exporter: '0'
  HTTP::Date: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/reyjrar/Parse-Syslog-Line
  repository: https://github.com/reyjrar/Parse-Syslog-Line.git
version: '2.8'
x_Dist_Zilla:
  perl:
    version: '5.020001'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
      name: '@Basic/GatherDir'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Basic/PruneCruft'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Basic/ManifestSkip'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Basic/MetaYAML'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Basic/License'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Basic/Readme'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Basic/ExtraTests'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Basic/ExecDir'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Basic/ShareDir'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Basic/MakeMaker'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Basic/Manifest'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Basic/TestRelease'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Basic/ConfirmRelease'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Basic/UploadToCPAN'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: '0.007'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::VersionFromModule
      name: VersionFromModule
      version: '0.08'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.008'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.008'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.008'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.008'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.008'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.008'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.008'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.008'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.008'
      name: PodWeaver
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: ReadmeMarkdownFromPod
      version: '0.141140'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: CopyFilesFromBuild
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
      name: Test::EOL
      version: '0.16'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: '0'
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: '0'
          phase: test
          script_finder:
            - ':ExecFiles'
          skips: []
      name: Test::Compile
      version: '2.051'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Check'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Commit'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v2.8
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Tag'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Push'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.025'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.025'
